### PR TITLE
Publish Test Results to PR

### PR DESCRIPTION
**Pull request by cmeyertons**
I saw in my recent PR that some tests failed and it was not easy to see how many, etc at a glance (you had to parse the output logs).

We have used this action with success in our company, it produces a PR comment with the test results that self-updates on each run.

It looks like this: 

image

Feel free to ignore, but figured this might be a QOL improvement for the team.  Cheers!

### CODE REVIEW

**Comment by jodydonetti** [comment]
Thanks @cmeyertons , I'll try and see how it goes, thanks!

**Comment by cmeyertons** [comment]
thanks for running the pipeline, has some failures due to specifying `--output` will fix

**Comment by cmeyertons** [comment]
@jodydonetti this ones good to go, just doesn’t run right on a fork.

**Review by jodydonetti — APPROVED** [review]
LGTM, let's merge and try it on main

**Pull request merged**
