### PR TITLE
docs: update DiskCache.md

### PR DESCRIPTION
**Pull request by GustavEikaas**
Nitpicky PR but found a strangely formulated sentence and couldnt help myself. 
Could alternatively be formulated as `"When aiming to ease cold starts without requiring multi-node support, an SQLite-based implementation of IDistributedCache can be used."`

### CODE REVIEW

**Review by jodydonetti — APPROVED** [review]
LGTM

**Comment by GustavEikaas** [comment]
Great!
Awesome library by the way! Been using it a lot and really fell in love with it! Keep up the good work💪

**Comment by jodydonetti** [comment]
> ... and couldnt help myself

ahah you're totally right 🤣, I missed that thanks!

> ... and couldnt help myself

*couldn't

sorry @GustavEikaas , I **had** to 😅

**Comment by jodydonetti** [comment]
> Great! Awesome library by the way! Been using it a lot and really fell in love with it! Keep up the good work💪

Thanks, really appreciate it!

If you have some spare time and play with [v2](https://github.com/ZiggyCreatures/FusionCache/milestone/15) let me know how you feel about it.
Last preview is [preview-3](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v2.0.0-preview-3), and I'll release preview-4 in the next few days: can't wait to go GA very very soon.

In any case thanks for the PR!

**Pull request merged**
