### PR TITLE
Improve the performance of the FusionCacheProvider

### PR DESCRIPTION
**Pull request by 0xced**
Storing the caches in a dictionary upfront allows to retrieve the cache in O(1) instead of O(n).

Using `Lazy<IFusionCache>` allows to preserve the semantic of throwing when accessing the (incorrectly configured) caches.

Also, the `DependencyInjectionTests` were very slightly improved:
* Using `GetRequiredService` instead of `GetService` plus the null-forgiving operator because an `InvalidOperationException` is always better than a `NullReferenceException`, even in unit tests.
* A new assertion was added to ensure that the default `IFusionCache` instance is always the same no matter how it's retrieved, either through `IFusionCacheProvider` or directly by requesting the `IFusionCache`.

### CODE REVIEW

**Comment by jodydonetti** [comment]
Hi @0xced I updated this branch based on the new main, and pushed some changes which build upon your work and can make it even better.

Basically instead of storing an IEnumerable to iterate on at every `GetCache()` call, I just stored either a single `LazyNamedCache` in case there was only one, or `null` in case they were more than 1: in this way no need to an iteration per-call, less cpu usage and less allocations.

Finally I've made the tests a little better around these scenarios.

Thoughts?

**Review by jodydonetti — APPROVED** [review]
With the latest changes it LGTM: if you agree I can proceed and merge this.

**Comment by 0xced** [comment]
Looks good to me too!

**Comment by jodydonetti** [comment]
Hi @0xced , [v1.3.0](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v1.3.0) is out 🥳

**Pull request merged**
